### ISSUE TITLE
Problem with rendering ports

### ISSUE THREAD

**Issue by MAKolker** [zHaytam/Blazor.Diagrams#78]
Hi. I'm trying to create custom node, but ports are not rendering.
Here is the style:
```
.diamond {
    position: relative;
    height: 100px;
    width: 100px;
    line-height: 100px;
    text-align: center;
    margin: 10px 40px;
}
.diamond:before {
    position: absolute;
    content: '';
    top: 0px;
    left: 0px;
    height: 100%;
    width: 100%;
    transform: rotateX(45deg) rotateZ(45deg);
    box-shadow: 0px 0px 12px gray;
}
.diamond:after {
    position: absolute;
    top: 10px;
    left: 10px;
    content: '';
    height: calc(100% - 22px);  /* -22px is 2 * 10px gap on either side - 2px border on either side */
    width: calc(100% - 22px);  /* -22px is 2 * 10px gap on either side - 2px border on either side */
    border: 1px solid orange;
    transform: rotateX(45deg) rotateZ(45deg);
}

.diamond.selected {
    border: 1px #4582ec solid;
}

.diamond:hover .port {
    visibility: visible;
}

.diamond .port {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background-color: #f5f5f5;
    border: 1px solid #d4d4d4;
    cursor: pointer;
    visibility: hidden;
}

 .diamond .port:hover, .node > .diamond .port.has-links {
    visibility: visible;
    background-color: black;
}

 .diamond .port.bottom {
    position: absolute;
    bottom: -10px;
    left: 40px;
}

 .diamond .port.top {
    position: absolute;
    top: -10px;
    left: 40px;
}
.diamond .port.right {
    position: absolute;
    top: 40px;
    right: -20px;
}
.diamond .port.left {
    position: absolute;
    top: 40px;
    left: -20px;
}
```
Node itself is drawn perfectly, but ports are missing. "::deep" not solving the problem.

**Comment by zHaytam** [comment]
Hello, I'll need a bit more information.
What's the HTML of your node (assuming it's a custom one)?

**Comment by MAKolker** [comment]
Here. I copied it from example in documentation
```
<div class="diamond @(Node.Selected ? "selected" : "")">
    @Node.Condition
    
    @foreach (var port in Node.Ports)
    {
        <PortRenderer Port="port"></PortRenderer>
    }
</div>

@code {

    [Parameter]
    public GatewayNode Node { get; set; }

}
```

**Comment by zHaytam** [comment]
This is a problem with CSS isolation...

**Comment by zHaytam** [comment]
This CSS works:
```css
.diamond {
    position: relative;
    height: 100px;
    width: 100px;
    line-height: 100px;
    text-align: center;
    margin: 10px 40px;
}

    .diamond:before {
        position: absolute;
        content: '';
        top: 0px;
        left: 0px;
        height: 100%;
        width: 100%;
        transform: rotateX(45deg) rotateZ(45deg);
        box-shadow: 0px 0px 12px gray;
    }

    .diamond:after {
        position: absolute;
        top: 10px;
        left: 10px;
        content: '';
        height: calc(100% - 22px); /* -22px is 2 * 10px gap on either side - 2px border on either side */
        width: calc(100% - 22px); /* -22px is 2 * 10px gap on either side - 2px border on either side */
        border: 1px solid orange;
        transform: rotateX(45deg) rotateZ(45deg);
    }

    .diamond.selected {
        border: 1px #4582ec solid;
    }

    .diamond:hover .port {
        visibility: visible;
    }

::deep.diamond .port {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background-color: #f5f5f5;
    border: 1px solid #d4d4d4;
    cursor: pointer;
    visibility: hidden;
}

    ::deep.diamond .port:hover, .node > .diamond .port.has-links {
        visibility: visible;
        background-color: black;
    }

    ::deep.diamond .port.bottom {
        position: absolute;
        bottom: -10px;
        left: 40px;
    }

    ::deep.diamond .port.top {
        position: absolute;
        top: -10px;
        left: 40px;
    }

    ::deep.diamond .port.right {
        position: absolute;
        top: 40px;
        right: -20px;
    }

    ::deep.diamond .port.left {
        position: absolute;
        top: 40px;
        left: -20px;
    }
```

Notice that it's `::deep.diamond`, without a space.
Although this still doesn't show ports, but I guess you know that since you're using hidden visibility.
